FROM ppodgorsek/robot-framework:latest
# FROM docker:latest
# FROM ubuntu:20.04

USER root

VOLUME /opt/robotframework/tests

WORKDIR /opt/robotframework

# ADD https://chromedriver.storage.googleapis.com/104.0.5112.79/chromedriver_linux64.zip /opt/robotframework/bin

# RUN curl -O https://chromedriver.storage.googleapis.com/104.0.5112.79/chromedriver_linux64.zip

# Mise à jour des programme du container
# RUN apt-get -y update
# RUN apt-get -y upgrade

# ARG DEBIAN_FRONTEND=noninteractive 

# RUN apt-get install -y git

# RUN git clone https://github.com/nicotrorigolo/robot_jenkins.git

CMD ["sleep", "3600"]