# FROM python:slim-buster
FROM python:3.11-rc-slim-buster

# # Setup X Window Virtual Framebuffer
# ENV SCREEN_COLOUR_DEPTH 24
# ENV SCREEN_HEIGHT 1080
# ENV SCREEN_WIDTH 1920

# # Define the default user who'll run the tests
# ENV ROBOT_UID 1000
# ENV ROBOT_GID 1000

# ARG DEBIAN_FRONTEND=noninteractive 

RUN apt-get -y update
RUN apt-get -y upgrade

# # WORKDIR /opt

# # RUN apt-get install -y wget
# # RUN wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
# # RUN apt-get install -y ./google-chrome-stable_current_amd64.deb

# RUN apt-get install  -y \
#     wget \
#     curl \
#     nano \
#     unzip \
#     openssh-client \
#     firefox-esr \
#     xvfb \
#     xsel \
#     libncurses5 \
#     libxml2-dev \
#     libxslt-dev \
#     libz-dev \
#     xclip \
#     fonts-takao-mincho \
#     fonts-takao \
#     make \
#     git \
#     jq \
#     gnupg2 \
# && rm -rf /var/lib/apt/lists/*  \
# && apt-get clean && apt-get autoremove -y

# RUN echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list \
#     && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
# RUN apt-get update && apt-get install -y google-chrome-stable


# RUN wget -q https://chromedriver.storage.googleapis.com/104.0.5112.79/chromedriver_linux64.zip -O /tmp/chromedriver_linux64.zip \
#     && unzip -qq /tmp/chromedriver_linux64.zip -d /usr/local/bin \
#     && rm /tmp/chromedriver_linux64.zip \
#     && chmod +x /usr/local/bin/chromedriver

# # Install Robotframework

# RUN pip install  \
#     requests \
#     robotframework \
#     selenium \
#     robotframework-seleniumlibrary \
#     robotframework-pabot==1.11 \
#     urllib3 \
#     awscli \
#     robotframework-requests \
#     robotframework-metrics \
#     robotframework-jsonlibrary \
#     xunitmerge \
#     boto3 \
#     awscli \
#     aws-request-signer \
#     aws-requests-auth \
#     requests-aws-sign \
#     robotframework-aws \
#     robotframework-databaselibrary \
#     requests-aws-sign \
#     sshtunnel \
#     setuptools \
#     PyMySQL \
#     requests_oauthlib


# # RUN wget -q https://chromedriver.storage.googleapis.com/104.0.5112.79/chromedriver_linux64.zip -O /tmp/chromedriver.zip \
# # && unzip /tmp/chromedriver.zip -d /usr/bin/ \
# # && rm -rf /tmp/chromedriver.zip

# # USER 1000:1000
# WORKDIR /data
# RUN git clone https://github.com/nicotrorigolo/robot_jenkins.git
# RUN mv robot_jenkins/Tests/test_robot_google.robot .

# ###################
# # c'est ok DEBUT
# ###################

# RUN apt-get install -y git

# RUN git clone https://github.com/nicotrorigolo/robot_jenkins.git
# RUN mv robot_jenkins/tests/test_robot_google.robot .
# RUN mv robot_jenkins/requirements.txt .
# RUN mv robot_jenkins/tests/aaa.robot .
# RUN mv robot_jenkins/chromeConfiguration.py .

# # COPY src/env/drivers/Linux/chromedriver /usr/local/bin

# RUN chmod +x /usr/local/bin/

# # Install python packages
# RUN /usr/local/bin/python -m pip install --upgrade pip
# RUN pip install -r requirements.txt

# # Install dependencies of Chrome driver and chrome
# # Notice that xvfb is an in-memory display server for Linux
# RUN apt-get update && \
#     apt-get install -y libnss3 libdbus-1-dev && \
#     apt-get install -y xdg-utils libgbm1 libasound2 fonts-liberation xvfb wget unzip

# # Install google-chrome-driver
# RUN wget -q https://chromedriver.storage.googleapis.com/104.0.5112.79/chromedriver_linux64.zip
# RUN unzip chromedriver_linux64.zip \
#     && rm chromedriver_linux64.zip

# # (Optional) Start dbus in WSL, see https://github.com/microsoft/WSL/issues/376#issuecomment-295933508
# RUN /etc/init.d/dbus start

# # Install google-chrome
# RUN apt-get install -y wget
# RUN wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
# RUN apt-get install -y ./google-chrome-stable_current_amd64.deb


# ENV PATH=/usr/local/bin:$PATH

# # CMD ["sleep", "3600"]


# ###################
# # c'est ok FIN
# ###################




RUN apt-get install -y git

RUN git clone https://github.com/nicotrorigolo/robot_jenkins.git
RUN mv robot_jenkins/tests/test_robot_google.robot .
RUN mv robot_jenkins/requirements.txt .
RUN mv robot_jenkins/tests/aaa.robot .
RUN mv robot_jenkins/chromeConfiguration.py .

RUN pip install  \
    robotframework \
    robotframework-seleniumlibrary

# Install dependencies of Chrome driver and chrome
# Notice that xvfb is an in-memory display server for Linux
RUN apt-get update && \
    apt-get install -y libnss3 libdbus-1-dev && \
    apt-get install -y xdg-utils libgbm1 libasound2 fonts-liberation xvfb wget unzip

# Install google-chrome-driver
RUN wget -q https://chromedriver.storage.googleapis.com/105.0.5195.52/chromedriver_linux64.zip
RUN unzip chromedriver_linux64.zip \
    && rm chromedriver_linux64.zip

# (Optional) Start dbus in WSL, see https://github.com/microsoft/WSL/issues/376#issuecomment-295933508
RUN /etc/init.d/dbus start

# Install google-chrome
RUN apt-get install -y wget
RUN wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN apt-get install -y ./google-chrome-stable_current_amd64.deb















CMD ["sleep", "3600"]
